### PR TITLE
Support passport 12

### PR DESCRIPTION
**Pull request by maximepvrt**

### CODE REVIEW

**Comment by maximepvrt** [comment]
@adaojunior can you merge and relaase this PR 🙏 thanks

**Review by adaojunior — APPROVED** [review]

**Comment by adaojunior** [comment]
Done! Thank you!

**Comment by maximepvrt** [comment]
Perfect, thanks. Can you release it ?

**Comment by adaojunior** [comment]
Hey, sorry about that. I just released it. Thank you again.

**Pull request merged**
